version: '3.9'
services:
  smokeping:
    image: linuxserver/smokeping:2.7.3
    restart: always
    hostname: smokeping
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - "./volumes/smokeping_config:/config"
      - "./volumes/smokeping_data:/data"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
